// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoneContacts.Models;

namespace PhoneContacts.Migrations
{
    [DbContext(typeof(PhoneContext))]
    partial class PhoneContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PhoneContacts.Models.Phone", b =>
                {
                    b.Property<int>("PhoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PhoneNum")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.HasKey("PhoneId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            PhoneId = 4,
                            Address = "123 Main St",
                            Name = "Peter Pan",
                            Notes = "Contact on Monday",
                            PhoneNum = 5155552314L
                        },
                        new
                        {
                            PhoneId = 3,
                            Address = "555 Gingerbread Lane",
                            Name = "Jack Beanstalk",
                            Notes = "Meet for Lunch",
                            PhoneNum = 5558675309L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
